include(
    ":app",
    ":feature:home",
    ":feature:session",
    ":base",
    ":data:db",
    ":data:db-room",
    ":data:repository",
    ":data:model",
    ":data:api",
    ":platform:parser"
)
