name: FOSDEM Event iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs
      - ios
env:
  GITHUB_CLIENT_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_KEY }}

jobs:
  ios-debug:
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      TERM: dumb

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup

    - name: Cleanup Disk space in runner
      run: .github/scripts/mac-disk-cleanup.sh

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-disabled: true

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - run: brew install swiftlint

    - name: Run Fastlane Lint lane
      run: bundle exec fastlane ios lint

    - name: Build iOS application
      run: bundle exec fastlane ios build_qa

    - name: Upload build outputs
      if: always()
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: ios-qa-build-outputs
        path: |
          *.ipa
          *.dSYM.zip

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-qa-logs
        path: |
          **/fastlane-buildlog
